# Change these first
owner: StreamOfRon # Your GitHub organization or username, where this repository lives
repo: macaw-social-status # The name of this repository

sites:
  - name: Macaw-Social Homepage
    url: https://macaw.social
  - name: Macaw-Social Static Object
    url: https://macaw.social/emoji/1f346.svg
  - name: Macaw-Social CDN Object
    url: https://macawsocial.sfo3.cdn.digitaloceanspaces.com/accounts/avatars/109/275/542/085/388/685/original/a655926f7c4a560a.png
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.macaw.social
  #baseUrl: /macaw-social-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Macaw-Social Status
  introTitle: Historical status and open issues for Macaw-Social
  introMessage: ""
  theme: dark
  navbar:
    - title: Macaw-Social
      href: https://macaw.social
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - StreamOfRon

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
